<!DOCTYPE nmaprun [
        <!ELEMENT nmaprun (host|runstats|finished|hosts)*>
        <!ELEMENT host (status|address|hostnames|ports|os|uptime|tcpsequence|ipidsequence|tcptssequence)*>
        <!ATTLIST host
                comment CDATA #REQUIRED>
        <!ELEMENT status (#PCDATA)>
        <!ATTLIST status
                state CDATA #REQUIRED>
        <!ELEMENT address (#PCDATA)>
        <!ATTLIST address
                addr CDATA #REQUIRED
                addrtype CDATA #REQUIRED
                vendor CDATA #REQUIRED>
        <!ELEMENT hostnames (#PCDATA)>
        <!ELEMENT ports (extraports|port)*>
        <!ELEMENT extraports (#PCDATA)>
        <!ATTLIST extraports
                count CDATA #REQUIRED
                state CDATA #REQUIRED>
        <!ELEMENT port (state|service)*>
        <!ATTLIST port
                portid CDATA #REQUIRED
                protocol CDATA #REQUIRED>
        <!ELEMENT state (#PCDATA)>
        <!ATTLIST state
                reason CDATA #REQUIRED
                reason_ttl CDATA #REQUIRED
                state CDATA #REQUIRED>
        <!ELEMENT service (#PCDATA)>
        <!ATTLIST service
                conf CDATA #REQUIRED
                extrainfo CDATA #IMPLIED
                method CDATA #REQUIRED
                name CDATA #REQUIRED
                product CDATA #IMPLIED
                version CDATA #IMPLIED>
        <!ELEMENT os (portused|osmatch)*>
        <!ELEMENT portused (#PCDATA)>
        <!ATTLIST portused
                portid CDATA #REQUIRED
                proto CDATA #REQUIRED
                state CDATA #REQUIRED>
        <!ELEMENT osmatch (osclass)*>
        <!ATTLIST osmatch
                accuracy CDATA #REQUIRED
                line CDATA #REQUIRED
                name CDATA #REQUIRED>
        <!ELEMENT osclass (#PCDATA)>
        <!ATTLIST osclass
                accuracy CDATA #REQUIRED
                osfamily CDATA #REQUIRED
                osgen CDATA #REQUIRED
                type CDATA #REQUIRED
                vendor CDATA #REQUIRED>
        <!ELEMENT uptime (#PCDATA)>
        <!ATTLIST uptime
                lastboot CDATA #REQUIRED
                seconds CDATA #REQUIRED>
        <!ELEMENT tcpsequence (#PCDATA)>
        <!ATTLIST tcpsequence
                difficulty CDATA #REQUIRED
                index CDATA #REQUIRED
                values CDATA #REQUIRED>
        <!ELEMENT ipidsequence (#PCDATA)>
        <!ATTLIST ipidsequence
                class CDATA #REQUIRED
                values CDATA #REQUIRED>
        <!ELEMENT tcptssequence (#PCDATA)>
        <!ATTLIST tcptssequence
                class CDATA #REQUIRED
                values CDATA #REQUIRED>
        <!ELEMENT runstats (#PCDATA)>
        <!ELEMENT finished (#PCDATA)>
        <!ATTLIST finished
                timestr CDATA #REQUIRED
                time CDATA #REQUIRED>
        <!ELEMENT hosts (#PCDATA)>
        <!ATTLIST hosts
                down CDATA #REQUIRED
                total CDATA #REQUIRED
                up CDATA #REQUIRED>
        ]>
<nmaprun>
    <host comment="">
        <status state="up"></status>
        <address addrtype="ipv4" vendor="" addr="192.168.9.1"></address>
        <address addrtype="mac" vendor="" addr="80:81:00:CB:9E:81"></address>
        <hostnames></hostnames>
        <ports>
            <extraports count="99" state="closed"></extraports>
            <port protocol="tcp" portid="80">
                <state reason="syn-ack" state="open" reason_ttl="128"></state>
                <service method="table" conf="3" name="http"></service>
            </port></ports>
        <os>
            <portused state="open" portid="80" proto="tcp"></portused>
            <portused state="closed" portid="7" proto="tcp"></portused>
            <portused state="closed" portid="35629" proto="udp"></portused>
            <osmatch line="61548" name="OpenWrt Kamikaze 8.09 (Linux 2.6.26)" accuracy="95">
                <osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="95"></osclass>
            </osmatch>
            <osmatch line="102410" name="Thecus 4200 or N5500 NAS device (Linux 2.6.33)" accuracy="94">
                <osclass type="storage-misc" osfamily="embedded" vendor="Thecus" osgen="" accuracy="94"></osclass>
            </osmatch>
            <osmatch line="59477" name="OpenWrt Kamikaze - Backfire or SuperMicro BMC (Linux 2.6.19 - 2.6.32)" accuracy="93">
                <osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="93"></osclass>
            </osmatch>
            <osmatch line="50222" name="Linux 2.6.18 - 2.6.32" accuracy="92">
                <osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="92"></osclass>
            </osmatch>
            <osmatch line="46802" name="OpenWrt Kamikaze 8.09 (Linux 2.4.35.4)" accuracy="91">
                <osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass>
            </osmatch><osmatch line="30737" name="Android 2.2 (Linux 2.6.32)" accuracy="91"><osclass type="phone" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="46692" name="OpenWrt (Linux 2.4.30 - 2.4.34)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="46838" name="OpenWrt White Russian 0.9 (Linux 2.4.30)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="52755" name="Linux 2.6.26" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="57316" name="Linux 2.6.35" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="183" values="97C70ADB,97C92A9A,97D69533,989BA699,995D3397,99570E0E" difficulty="Good luck!"></tcpsequence><ipidsequence values="0,0,0,0,0,0" class="All zeros"></ipidsequence><tcptssequence values="" class="none returned (unsupported)"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.23"></address><address addrtype="mac" vendor="" addr="80:81:00:05:C5:81"></address><hostnames></hostnames><ports><extraports count="99" state="closed"></extraports><port protocol="tcp" portid="80"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="http"></service></port></ports><os><portused state="open" portid="80" proto="tcp"></portused><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="40985" proto="udp"></portused><osmatch line="56530" name="Linux 2.6.32 - 3.10" accuracy="99"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="3.X" accuracy="99"></osclass></osmatch><osmatch line="68429" name="Rebranded surveillance DVR (Hikvision, Q-SEE, EYEsurv, A1Webcams, Foscam)" accuracy="96"><osclass type="specialized" osfamily="Linux" vendor="Linux" osgen="" accuracy="96"></osclass></osmatch><osmatch line="64667" name="Linux 3.2" accuracy="95"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="3.X" accuracy="95"></osclass></osmatch><osmatch line="62038" name="OpenWrt (Linux 3.3)" accuracy="95"><osclass type="broadband router" osfamily="Linux" vendor="Linux" osgen="3.X" accuracy="95"></osclass></osmatch><osmatch line="62920" name="Linux 3.1" accuracy="94"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="3.X" accuracy="94"></osclass></osmatch><osmatch line="30460" name="Geovision EBD4700 CCTV camera (Linux 3.4)" accuracy="94"><osclass type="webcam" osfamily="Linux" vendor="Linux" osgen="3.X" accuracy="94"></osclass></osmatch><osmatch line="68310" name="Dahua or Amcrest network video recorder (Linux)" accuracy="94"><osclass type="media device" osfamily="Linux" vendor="Linux" osgen="" accuracy="94"></osclass></osmatch><osmatch line="105001" name="Western Digital My Cloud DL4100 NAS (Linux 3.10)" accuracy="94"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="3.X" accuracy="94"></osclass></osmatch><osmatch line="61818" name="AXIS 210A or 211 Network Camera (Linux 2.6.17)" accuracy="94"><osclass type="webcam" osfamily="embedded" vendor="AXIS" osgen="" accuracy="94"></osclass></osmatch><osmatch line="56249" name="Linux 2.6.32" accuracy="94"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="94"></osclass></osmatch></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="233" values="E5144ACF,B2371200,4AAFF554,2790E1C3,D41FA6E6,FF1ECA56" difficulty="Good luck!"></tcpsequence><ipidsequence values="0,0,0,0,0,0" class="All zeros"></ipidsequence><tcptssequence values="" class="none returned (unsupported)"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.25"></address><address addrtype="mac" vendor="" addr="80:81:00:CE:74:81"></address><hostnames></hostnames><ports><extraports count="99" state="closed"></extraports><port protocol="tcp" portid="80"><state reason="syn-ack" state="open" reason_ttl="128"></state><service method="table" conf="3" name="http"></service></port></ports><os><portused state="open" portid="80" proto="tcp"></portused><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="36468" proto="udp"></portused><osmatch line="61548" name="OpenWrt Kamikaze 8.09 (Linux 2.6.26)" accuracy="95"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="95"></osclass></osmatch><osmatch line="102410" name="Thecus 4200 or N5500 NAS device (Linux 2.6.33)" accuracy="94"><osclass type="storage-misc" osfamily="embedded" vendor="Thecus" osgen="" accuracy="94"></osclass></osmatch><osmatch line="59477" name="OpenWrt Kamikaze - Backfire or SuperMicro BMC (Linux 2.6.19 - 2.6.32)" accuracy="93"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="93"></osclass></osmatch><osmatch line="50222" name="Linux 2.6.18 - 2.6.32" accuracy="92"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="92"></osclass></osmatch><osmatch line="30737" name="Android 2.2 (Linux 2.6.32)" accuracy="91"><osclass type="phone" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="46692" name="OpenWrt (Linux 2.4.30 - 2.4.34)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="46838" name="OpenWrt White Russian 0.9 (Linux 2.4.30)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="46802" name="OpenWrt Kamikaze 8.09 (Linux 2.4.35.4)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="52755" name="Linux 2.6.26" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="57316" name="Linux 2.6.35" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="184" values="977111D9,978EF1D9,98B49EFE,98BBA098,995FADAE,9A0CDA42" difficulty="Good luck!"></tcpsequence><ipidsequence values="0,0,0,0,0,0" class="All zeros"></ipidsequence><tcptssequence values="" class="none returned (unsupported)"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.26"></address><address addrtype="mac" vendor="" addr="80:81:00:CF:08:81"></address><hostnames></hostnames><ports><extraports count="99" state="closed"></extraports><port protocol="tcp" portid="80"><state reason="syn-ack" state="open" reason_ttl="128"></state><service method="table" conf="3" name="http"></service></port></ports><os><portused state="open" portid="80" proto="tcp"></portused><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="34620" proto="udp"></portused><osmatch line="61548" name="OpenWrt Kamikaze 8.09 (Linux 2.6.26)" accuracy="94"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="94"></osclass></osmatch><osmatch line="102410" name="Thecus 4200 or N5500 NAS device (Linux 2.6.33)" accuracy="94"><osclass type="storage-misc" osfamily="embedded" vendor="Thecus" osgen="" accuracy="94"></osclass></osmatch><osmatch line="59477" name="OpenWrt Kamikaze - Backfire or SuperMicro BMC (Linux 2.6.19 - 2.6.32)" accuracy="93"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="93"></osclass></osmatch><osmatch line="50222" name="Linux 2.6.18 - 2.6.32" accuracy="92"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="92"></osclass></osmatch><osmatch line="46692" name="OpenWrt (Linux 2.4.30 - 2.4.34)" accuracy="92"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="92"></osclass></osmatch><osmatch line="46838" name="OpenWrt White Russian 0.9 (Linux 2.4.30)" accuracy="92"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="92"></osclass></osmatch><osmatch line="46802" name="OpenWrt Kamikaze 8.09 (Linux 2.4.35.4)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="52755" name="Linux 2.6.26" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="57316" name="Linux 2.6.35" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="104518" name="Vodafone Easybox 904 xDSL WAP (Linux 2.6.32)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="181" values="97CE9B78,9783EF20,97F20772,989F376B,9998D97B,99D5E2BF" difficulty="Good luck!"></tcpsequence><ipidsequence values="0,0,0,0,0,0" class="All zeros"></ipidsequence><tcptssequence values="" class="none returned (unsupported)"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.37"></address><address addrtype="mac" vendor="Realtek Semiconductor" addr="00:E0:4C:08:DC:C4"></address><hostnames></hostnames><ports><extraports count="92" state="closed"></extraports><port protocol="tcp" portid="135"><state reason="no-response" state="filtered" reason_ttl="0"></state><service method="table" conf="3" name="msrpc"></service></port><port protocol="tcp" portid="139"><state reason="no-response" state="filtered" reason_ttl="0"></state><service method="table" conf="3" name="netbios-ssn"></service></port><port protocol="tcp" portid="445"><state reason="no-response" state="filtered" reason_ttl="0"></state><service method="table" conf="3" name="microsoft-ds"></service></port><port protocol="tcp" portid="1433"><state reason="syn-ack" state="open" reason_ttl="64"></state><service product="Microsoft SQL Server 2000" version="8.00.2039; SP4" method="probed" conf="10" name="ms-sql-s"></service></port><port protocol="tcp" portid="49152"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="unknown"></service></port><port protocol="tcp" portid="49153"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="unknown"></service></port><port protocol="tcp" portid="49154"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="unknown"></service></port><port protocol="tcp" portid="49156"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="unknown"></service></port></ports><os><portused state="open" portid="1433" proto="tcp"></portused><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="34440" proto="udp"></portused><osmatch line="79826" name="Microsoft Windows Vista" accuracy="98"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="Vista" accuracy="98"></osclass></osmatch><osmatch line="80364" name="Microsoft Windows Vista, Windows 7 SP1, or Windows 8.1 Update 1" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="8.1" accuracy="95"></osclass></osmatch><osmatch line="79996" name="Microsoft Windows Vista SP0 - SP2, Windows Server 2008, or Windows 7 Ultimate" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="95"></osclass></osmatch><osmatch line="80256" name="Microsoft Windows Vista SP2" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="Vista" accuracy="95"></osclass></osmatch><osmatch line="77144" name="Microsoft Windows 7 SP0 - SP1" accuracy="94"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="94"></osclass></osmatch><osmatch line="77531" name="Microsoft Windows 7 SP1" accuracy="94"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="94"></osclass></osmatch><osmatch line="77069" name="Microsoft Windows 7 Professional SP1" accuracy="94"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="94"></osclass></osmatch><osmatch line="80179" name="Microsoft Windows Vista SP1 - SP2, Windows Server 2008 SP2, or Windows 7" accuracy="94"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="94"></osclass></osmatch><osmatch line="76624" name="Microsoft Windows 7" accuracy="92"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="92"></osclass></osmatch><osmatch line="69361" name="Microsoft Windows 10" accuracy="92"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="10" accuracy="92"></osclass></osmatch></os><uptime lastboot="Thu Dec 03 09:15:36 2020" seconds="7125"></uptime><tcpsequence index="235" values="52DA85D8,ACD47A2B,AEB05377,F2F87185,446D7244,FAED2797" difficulty="Good luck!"></tcpsequence><ipidsequence values="22D0,22E1,22EC,22EE,22F0,22F2" class="Busy server or unknown class"></ipidsequence><tcptssequence values="AD08F,AD131,AD19C,AD1EF,AD23C,AD286" class="100HZ"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.38"></address><address addrtype="mac" vendor="Realtek Semiconductor" addr="00:E0:4C:08:DC:B5"></address><hostnames></hostnames><ports><extraports count="95" state="closed"></extraports><port protocol="tcp" portid="135"><state reason="no-response" state="filtered" reason_ttl="0"></state><service method="table" conf="3" name="msrpc"></service></port><port protocol="tcp" portid="139"><state reason="no-response" state="filtered" reason_ttl="0"></state><service method="table" conf="3" name="netbios-ssn"></service></port><port protocol="tcp" portid="49152"><state reason="syn-ack" state="open" reason_ttl="128"></state><service method="table" conf="3" name="unknown"></service></port><port protocol="tcp" portid="49153"><state reason="syn-ack" state="open" reason_ttl="128"></state><service method="table" conf="3" name="unknown"></service></port><port protocol="tcp" portid="49154"><state reason="syn-ack" state="open" reason_ttl="128"></state><service method="table" conf="3" name="unknown"></service></port></ports><os><portused state="open" portid="49152" proto="tcp"></portused><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="30894" proto="udp"></portused><osmatch line="79996" name="Microsoft Windows Vista SP0 - SP2, Windows Server 2008, or Windows 7 Ultimate" accuracy="99"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="99"></osclass></osmatch><osmatch line="80179" name="Microsoft Windows Vista SP1 - SP2, Windows Server 2008 SP2, or Windows 7" accuracy="98"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="98"></osclass></osmatch><osmatch line="77423" name="Microsoft Windows 7 SP1" accuracy="96"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="96"></osclass></osmatch><osmatch line="75466" name="Microsoft Windows Server 2008 SP2 or Windows 10 or Xbox One" accuracy="96"><osclass type="media device" osfamily="embedded" vendor="Microsoft" osgen="" accuracy="96"></osclass></osmatch><osmatch line="75319" name="Microsoft Windows Server 2008 SP2" accuracy="96"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="2008" accuracy="96"></osclass></osmatch><osmatch line="75749" name="Microsoft Windows Server 2012 R2" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="2012" accuracy="95"></osclass></osmatch><osmatch line="76956" name="Microsoft Windows 7 or Windows Server 2008 R2" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="2008" accuracy="95"></osclass></osmatch><osmatch line="79944" name="Microsoft Windows Vista or Windows 7 SP1" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="7" accuracy="95"></osclass></osmatch><osmatch line="77165" name="Microsoft Windows 7 SP0 - SP1 or Windows Server 2008" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="2008" accuracy="95"></osclass></osmatch><osmatch line="77190" name="Microsoft Windows 7 SP0 - SP1, Windows Server 2008 SP1, Windows Server 2008 R2, Windows 8, or Windows 8.1 Update 1" accuracy="95"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="8.1" accuracy="95"></osclass></osmatch></os><uptime lastboot="Wed Dec 02 22:36:16 2020" seconds="45485"></uptime><tcpsequence index="237" values="B7C569D3,9E2442CE,B7822BE9,19264873,1067065B,F87B116E" difficulty="Good luck!"></tcpsequence><ipidsequence values="6AE8,6AE9,6AEE,6AF0,6AF1,6AF3" class="Incremental"></ipidsequence><tcptssequence values="455917,4559B7,455A28,455A76,455ACC,455B14" class="100HZ"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.46"></address><address addrtype="mac" vendor="Guangdong Oppo Mobile Telecommunications" addr="3C:F5:91:B3:74:6F"></address><hostnames></hostnames><ports><extraports count="100" state="closed"></extraports></ports><os><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="37594" proto="udp"></portused></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="" values="" difficulty=""></tcpsequence><ipidsequence values="" class=""></ipidsequence><tcptssequence values="" class=""></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.49"></address><address addrtype="mac" vendor="Guangdong Oppo Mobile Telecommunications" addr="18:D7:17:9B:D6:33"></address><hostnames></hostnames><ports><extraports count="99" state="closed"></extraports><port protocol="tcp" portid="5666"><state reason="no-response" state="filtered" reason_ttl="0"></state><service method="table" conf="3" name="nrpe"></service></port></ports><os><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="43667" proto="udp"></portused></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="" values="" difficulty=""></tcpsequence><ipidsequence values="" class=""></ipidsequence><tcptssequence values="" class=""></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.51"></address><address addrtype="mac" vendor="Realtek Semiconductor" addr="00:E0:4C:07:69:F1"></address><hostnames></hostnames><ports><extraports count="94" state="closed"></extraports><port protocol="tcp" portid="135"><state reason="syn-ack" state="open" reason_ttl="64"></state><service product="Microsoft Windows RPC" method="probed" conf="10" name="msrpc"></service></port><port protocol="tcp" portid="139"><state reason="syn-ack" state="open" reason_ttl="64"></state><service product="Microsoft Windows netbios-ssn" method="probed" conf="10" name="netbios-ssn"></service></port><port protocol="tcp" portid="445"><state reason="syn-ack" state="open" reason_ttl="64"></state><service product="Microsoft Windows 7 - 10 microsoft-ds" extrainfo="workgroup: WORKGROUP" method="probed" conf="10" name="microsoft-ds"></service></port><port protocol="tcp" portid="49152"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="unknown"></service></port><port protocol="tcp" portid="49153"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="unknown"></service></port><port protocol="tcp" portid="49154"><state reason="syn-ack" state="open" reason_ttl="64"></state><service method="table" conf="3" name="unknown"></service></port></ports><os><portused state="open" portid="135" proto="tcp"></portused><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="42605" proto="udp"></portused><osmatch line="80364" name="Microsoft Windows Vista, Windows 7 SP1, or Windows 8.1 Update 1" accuracy="100"><osclass type="general purpose" osfamily="Windows" vendor="Microsoft" osgen="8.1" accuracy="100"></osclass></osmatch></os><uptime lastboot="Thu Dec 03 07:30:47 2020" seconds="13414"></uptime><tcpsequence index="244" values="B6AD3A4D,6F3E229C,C622E0AD,430456AD,2FAC8926,9B9A4EAB" difficulty="Good luck!"></tcpsequence><ipidsequence values="152E,1531,1534,1535,1537,1538" class="Incremental"></ipidsequence><tcptssequence values="144960,14498F,1449C5,1449F1,144A29,144A60" class="100HZ"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.52"></address><address addrtype="mac" vendor="Huawei Technologies" addr="14:D1:69:34:F3:3D"></address><hostnames></hostnames><ports><extraports count="100" state="closed"></extraports></ports><os><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="30796" proto="udp"></portused></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="" values="" difficulty=""></tcpsequence><ipidsequence values="" class=""></ipidsequence><tcptssequence values="" class=""></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.57"></address><address addrtype="mac" vendor="" addr="80:81:00:CF:02:81"></address><hostnames></hostnames><ports><extraports count="99" state="closed"></extraports><port protocol="tcp" portid="80"><state reason="syn-ack" state="open" reason_ttl="128"></state><service method="table" conf="3" name="http"></service></port></ports><os><portused state="open" portid="80" proto="tcp"></portused><portused state="closed" portid="7" proto="tcp"></portused><portused state="closed" portid="35374" proto="udp"></portused><osmatch line="61548" name="OpenWrt Kamikaze 8.09 (Linux 2.6.26)" accuracy="94"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="94"></osclass></osmatch><osmatch line="102410" name="Thecus 4200 or N5500 NAS device (Linux 2.6.33)" accuracy="94"><osclass type="storage-misc" osfamily="embedded" vendor="Thecus" osgen="" accuracy="94"></osclass></osmatch><osmatch line="59477" name="OpenWrt Kamikaze - Backfire or SuperMicro BMC (Linux 2.6.19 - 2.6.32)" accuracy="93"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="93"></osclass></osmatch><osmatch line="50222" name="Linux 2.6.18 - 2.6.32" accuracy="92"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="92"></osclass></osmatch><osmatch line="46692" name="OpenWrt (Linux 2.4.30 - 2.4.34)" accuracy="92"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="92"></osclass></osmatch><osmatch line="30737" name="Android 2.2 (Linux 2.6.32)" accuracy="91"><osclass type="phone" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="46838" name="OpenWrt White Russian 0.9 (Linux 2.4.30)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="46802" name="OpenWrt Kamikaze 8.09 (Linux 2.4.35.4)" accuracy="91"><osclass type="WAP" osfamily="Linux" vendor="Linux" osgen="2.4.X" accuracy="91"></osclass></osmatch><osmatch line="52755" name="Linux 2.6.26" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch><osmatch line="57316" name="Linux 2.6.35" accuracy="91"><osclass type="general purpose" osfamily="Linux" vendor="Linux" osgen="2.6.X" accuracy="91"></osclass></osmatch></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="179" values="972B1453,97D8A089,98C1AE86,9877DB40,98DD23CC,99A6834E" difficulty="Good luck!"></tcpsequence><ipidsequence values="0,0,0,0,0,0" class="All zeros"></ipidsequence><tcptssequence values="" class="none returned (unsupported)"></tcptssequence></host><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="192.168.9.58"></address><address addrtype="mac" vendor="" addr="80:81:00:CC:54:81"></address><hostnames></hostnames><ports><extraports count="99" state="closed"></extraports><port protocol="tcp" portid="80"><state reason="syn-ack" state="open" reason_ttl="128"></state><service